//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Services {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeriodoEstudioAsignaturaIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodoEstudioAsignaturaIntegracionStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Services.PeriodoEstudioAsignaturaIntegracionStrings", typeof(PeriodoEstudioAsignaturaIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Asignatura de este Período de Estudio de Asignatura no está mapeada con la Asignatura Plan de esta Asignatura Ofertada.
        /// </summary>
        public static string ErrorAsignaturaEstudioNoMapeada {
            get {
                return ResourceManager.GetString("ErrorAsignaturaEstudioNoMapeada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Existe la Asignatura Ofertada en ERP.
        /// </summary>
        public static string ErrorAsignaturaOfertadaErpNoExiste {
            get {
                return ResourceManager.GetString("ErrorAsignaturaOfertadaErpNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Datos de Erp.
        /// </summary>
        public static string ErrorDatosErp {
            get {
                return ResourceManager.GetString("ErrorDatosErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Datos de Gestor.
        /// </summary>
        public static string ErrorDatosGestor {
            get {
                return ResourceManager.GetString("ErrorDatosGestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Existe el Período de Estudio de Asignatura.
        /// </summary>
        public static string ErrorPeriodoEstudioAsignaturaNoExiste {
            get {
                return ResourceManager.GetString("ErrorPeriodoEstudioAsignaturaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Existe el Período de Estudio de Asignatura en Gestor.
        /// </summary>
        public static string ErrorPeriodoEstudioAsignaturaUnirNoExiste {
            get {
                return ResourceManager.GetString("ErrorPeriodoEstudioAsignaturaUnirNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe otro Mapeo para este Período de Estudio de Asignatura.
        /// </summary>
        public static string ErrorPeriodoEstudioAsignaturaYaMapeada {
            get {
                return ResourceManager.GetString("ErrorPeriodoEstudioAsignaturaYaMapeada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Período de Estudio de este Período de Estudio de Asignatura no está mapeado con el Plan Ofertado de esta Asignatura Ofertada.
        /// </summary>
        public static string ErrorPeriodoEstudioNoMapeado {
            get {
                return ResourceManager.GetString("ErrorPeriodoEstudioNoMapeado", resourceCulture);
            }
        }
    }
}
