//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Services {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeriodoEstudioIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodoEstudioIntegracionStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Services.PeriodoEstudioIntegracionStrings", typeof(PeriodoEstudioIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Mapeo de Estudio para el Plan de Estudio de este Plan Ofertado.
        /// </summary>
        public static string ErrorEstudioNoExiste {
            get {
                return ResourceManager.GetString("ErrorEstudioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Estudio de este Período de Estudio no está mapeado con el Plan de Estudio de este Plan Ofertado.
        /// </summary>
        public static string ErrorMapeoEstudioConPlanEstudio {
            get {
                return ResourceManager.GetString("ErrorMapeoEstudioConPlanEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Período de Matriculación de este Período de Estudio no está mapeado con el Período Académico de este Plan Ofertado.
        /// </summary>
        public static string ErrorMapeoPeriodoMatriculacionConPeriodoAcademico {
            get {
                return ResourceManager.GetString("ErrorMapeoPeriodoMatriculacionConPeriodoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Existe el Período de Estudio.
        /// </summary>
        public static string ErrorPeriodoEstudioNoExiste {
            get {
                return ResourceManager.GetString("ErrorPeriodoEstudioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe otro Mapeo para este Período de Estudio.
        /// </summary>
        public static string ErrorPeriodoEstudioYaMapeado {
            get {
                return ResourceManager.GetString("ErrorPeriodoEstudioYaMapeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Mapeo de Plantilla de Estudio para el Plan de Estudio de este Plan Ofertado.
        /// </summary>
        public static string ErrorPlanNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlanNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Existe el Plan Ofertado en ERP.
        /// </summary>
        public static string ErrorPlanOfertadoErpNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlanOfertadoErpNoExiste", resourceCulture);
            }
        }
    }
}
