//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlantillaAsignaturaIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlantillaAsignaturaIntegracionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Services.PlantillaAsignaturaIntegracionStrings", typeof(PlantillaAsignaturaIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Existe la Asignatura Plan en ERP.
        /// </summary>
        public static string ErrorAsignaturaPlanErpNoExiste {
            get {
                return ResourceManager.GetString("ErrorAsignaturaPlanErpNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Existe la Asignatura Plan de Integracion.
        /// </summary>
        public static string ErrorAsignaturaPlanNoExiste {
            get {
                return ResourceManager.GetString("ErrorAsignaturaPlanNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro Mapeo para esta Asignatura Plan.
        /// </summary>
        public static string ErrorAsignaturaPlanYaMapeada {
            get {
                return ResourceManager.GetString("ErrorAsignaturaPlanYaMapeada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos enviados no son validos.
        /// </summary>
        public static string ErrorDatosEliminar {
            get {
                return ResourceManager.GetString("ErrorDatosEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Datos de Erp.
        /// </summary>
        public static string ErrorDatosErp {
            get {
                return ResourceManager.GetString("ErrorDatosErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Datos de Gestor.
        /// </summary>
        public static string ErrorDatosGestor {
            get {
                return ResourceManager.GetString("ErrorDatosGestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento Mapeo de Plantilla de Asignatura: &apos;{0}&apos; no se pudo eliminar. Causa: No es posible eliminar la relación con al menos un elemento {1} existente.
        /// </summary>
        public static string ErrorEliminar {
            get {
                return ResourceManager.GetString("ErrorEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible modificar la Plantilla de Asignatura debido a que tiene al menos un Mapeo de Asignatura relacionado.
        /// </summary>
        public static string ErrorModificarPorAsignaturaEstudioIntegracion {
            get {
                return ResourceManager.GetString("ErrorModificarPorAsignaturaEstudioIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un Mapeo de Plantilla de Estudio para el Plan de Estudio de esta Asignatura Plan.
        /// </summary>
        public static string ErrorPlanIntegracionDesdeAsignaturaPlanNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlanIntegracionDesdeAsignaturaPlanNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un Mapeo de Plan de Estudio para la Plantilla de Estudio de esta Plantilla de Asignatura.
        /// </summary>
        public static string ErrorPlanIntegracionDesdePlantillaAsignaturaNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlanIntegracionDesdePlantillaAsignaturaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Existe la Plantilla de Asignatura.
        /// </summary>
        public static string ErrorPlantillaAsignaturaNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlantillaAsignaturaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro Mapeo para esta Plantilla de Asignatura.
        /// </summary>
        public static string ErrorPlantillaAsignaturaYaMapeada {
            get {
                return ResourceManager.GetString("ErrorPlantillaAsignaturaYaMapeada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Plantilla de Estudio a la cual está asociado esta Plantilla de Asignatura en la aplicación de Gestión de Expedientes no coincide con la definida en el Mapeo de Plantilla de Estudio que mapea al Plan de Estudio de esta Asignatura Plan.
        /// </summary>
        public static string ErrorPlantillaEstudioNoCoincide {
            get {
                return ResourceManager.GetString("ErrorPlantillaEstudioNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeo de Asignatura.
        /// </summary>
        public static string LeyendaAsignaturaEstudioIntegracion {
            get {
                return ResourceManager.GetString("LeyendaAsignaturaEstudioIntegracion", resourceCulture);
            }
        }
    }
}
