//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlantillaEstudioIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlantillaEstudioIntegracionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Services.PlantillaEstudioIntegracionStrings", typeof(PlantillaEstudioIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos enviados no son validos.
        /// </summary>
        public static string ErrorDatosEliminar {
            get {
                return ResourceManager.GetString("ErrorDatosEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento Mapeo de Plantilla de Estudio: &apos;{0}&apos; no se pudo eliminar. Causa: No es posible eliminar la relación con al menos un elemento {1} existente..
        /// </summary>
        public static string ErrorEliminar {
            get {
                return ResourceManager.GetString("ErrorEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible modificar la Plantilla de Estudio debido a que tiene al menos un {0} relacionado..
        /// </summary>
        public static string ErrorModificar {
            get {
                return ResourceManager.GetString("ErrorModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el Plan de Estudio en ERP.
        /// </summary>
        public static string ErrorPlanEstudioErpNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlanEstudioErpNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro Mapeo para este Plan de Estudio.
        /// </summary>
        public static string ErrorPlanEstudioYaMapeado {
            get {
                return ResourceManager.GetString("ErrorPlanEstudioYaMapeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el Plan de Integracion.
        /// </summary>
        public static string ErrorPlanIntegracionNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlanIntegracionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la Plantilla de Estudio.
        /// </summary>
        public static string ErrorPlantillaEstudioNoExiste {
            get {
                return ResourceManager.GetString("ErrorPlantillaEstudioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro Mapeo para esta Plantilla de Estudio.
        /// </summary>
        public static string ErrorPlantillaEstudioYaMapeada {
            get {
                return ResourceManager.GetString("ErrorPlantillaEstudioYaMapeada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeo de Plantilla de Asignatura.
        /// </summary>
        public static string LeyendaAsignaturaPlanIntegracion {
            get {
                return ResourceManager.GetString("LeyendaAsignaturaPlanIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeo de Estudio.
        /// </summary>
        public static string LeyendaEstudioIntegracion {
            get {
                return ResourceManager.GetString("LeyendaEstudioIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeo de Período de Estudio.
        /// </summary>
        public static string LeyendaPeriodoEstudioIntegracion {
            get {
                return ResourceManager.GetString("LeyendaPeriodoEstudioIntegracion", resourceCulture);
            }
        }
    }
}
