$.Globalization.Page = {
    ColumnIdPerEstAsig: 'ID Per. Est. Asig.',
    ColumnAsignatura: 'Asignatura',
    ColumnEstudio: 'Estudio',
    ColumnPeriodoMatriculacion: 'Período Matriculación',
    ColumnIdAsigOf: 'ID Asig. Of.',
    ColumnAsignaturaOfertada: 'Asignatura Ofertada',
    ColumnPeriodoLectivo: 'Período Lectivo',
    ColumnPlanEstudio: 'Plan de Estudio',
    ColumnPeriodoAcademico: 'Período Académico',
    ColumnaPopupIdAsignaturaOfertada: 'ID Asig. Of.',
    ColumnaPopupAsignaturaOfertada: 'Asignatura Ofertada',
    ColumnaPopupPeriodoLectivo: 'Período Lectivo',
    ColumnaPopupPlanEstudio: 'Plan de Estudio',
    ColumnaPopupPeriodoAcademico: 'Período Académico',
    ColumnaPopupTipoAsignatura: 'Tipo Asignatura',
    ColumnaPopupCreditos: 'Créditos',
    ColumnaPopupDuracionPeriodoLectivo: 'Duración Período Lectivo',
    ColumnaPopupUbicacionPeriodoLectivo: 'Ubicación Período Lectivo',
    ColumnaPopupCurso: 'Curso',
    TituloPopupAsignaturaOfertada: 'Listado de Asignaturas Ofertadas',
    TituloPopupPeriodoEstudioAsignatura: 'Listado de Períodos de Estudios de Asignaturas',
    ErrorNoSeleccionPeriodoEstudioAsignatura: 'Debe seleccionar un Período de Estudio de Asignatura',
    ErrorNoSeleccionAsignaturaOfertada: 'Debe seleccionar una Asignatura Ofertada'
};