//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AsignaturaIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsignaturaIntegracionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Views.AsignaturaIntegracionStrings", typeof(AsignaturaIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string LabelActiva {
            get {
                return ResourceManager.GetString("LabelActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignatura.
        /// </summary>
        public static string LabelAsignatura {
            get {
                return ResourceManager.GetString("LabelAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignatura Plan.
        /// </summary>
        public static string LabelAsignaturaPlanErp {
            get {
                return ResourceManager.GetString("LabelAsignaturaPlanErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créditos.
        /// </summary>
        public static string LabelCreditos {
            get {
                return ResourceManager.GetString("LabelCreditos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créditos.
        /// </summary>
        public static string LabelCreditosErp {
            get {
                return ResourceManager.GetString("LabelCreditosErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string LabelCurso {
            get {
                return ResourceManager.GetString("LabelCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string LabelCursoErp {
            get {
                return ResourceManager.GetString("LabelCursoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración Período Lectivo.
        /// </summary>
        public static string LabelDuracionPeriodoLectivoErp {
            get {
                return ResourceManager.GetString("LabelDuracionPeriodoLectivoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string LabelEstudio {
            get {
                return ResourceManager.GetString("LabelEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Asignatura.
        /// </summary>
        public static string LabelIdAsignatura {
            get {
                return ResourceManager.GetString("LabelIdAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Asignatura Plan.
        /// </summary>
        public static string LabelIdAsignaturaPlanErp {
            get {
                return ResourceManager.GetString("LabelIdAsignaturaPlanErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Estudio.
        /// </summary>
        public static string LabelIdEstudio {
            get {
                return ResourceManager.GetString("LabelIdEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Plan de Estudio.
        /// </summary>
        public static string LabelIdPlanEstudioErp {
            get {
                return ResourceManager.GetString("LabelIdPlanEstudioErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período Lectivo.
        /// </summary>
        public static string LabelPeriodoLectivo {
            get {
                return ResourceManager.GetString("LabelPeriodoLectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Estudio.
        /// </summary>
        public static string LabelPlanEstudioErp {
            get {
                return ResourceManager.GetString("LabelPlanEstudioErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Asignatura en el Gestor UNIR.
        /// </summary>
        public static string LabelSeccionAsignatura {
            get {
                return ResourceManager.GetString("LabelSeccionAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Asignatura Plan en el ERP Académico.
        /// </summary>
        public static string LabelSeccionAsignaturaPlan {
            get {
                return ResourceManager.GetString("LabelSeccionAsignaturaPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Asignatura.
        /// </summary>
        public static string LabelTipoAsignatura {
            get {
                return ResourceManager.GetString("LabelTipoAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Asignatura.
        /// </summary>
        public static string LabelTipoAsignaturaErp {
            get {
                return ResourceManager.GetString("LabelTipoAsignaturaErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Mapeo de Asignatura.
        /// </summary>
        public static string LabelTituloPaginaAdicion {
            get {
                return ResourceManager.GetString("LabelTituloPaginaAdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Mapeo de Asignatura.
        /// </summary>
        public static string LabelTituloPaginaEdicion {
            get {
                return ResourceManager.GetString("LabelTituloPaginaEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Mapeos de Asignaturas.
        /// </summary>
        public static string LabelTituloPaginaListado {
            get {
                return ResourceManager.GetString("LabelTituloPaginaListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación Período Lectivo.
        /// </summary>
        public static string LabelUbicacionPeriodoLectivoErp {
            get {
                return ResourceManager.GetString("LabelUbicacionPeriodoLectivoErp", resourceCulture);
            }
        }
    }
}
