//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Views.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string LabelBuscar {
            get {
                return ResourceManager.GetString("LabelBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string LabelCancelar {
            get {
                return ResourceManager.GetString("LabelCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string LabelCrear {
            get {
                return ResourceManager.GetString("LabelCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string LabelEliminar {
            get {
                return ResourceManager.GetString("LabelEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string LabelFiltros {
            get {
                return ResourceManager.GetString("LabelFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string LabelGuardar {
            get {
                return ResourceManager.GetString("LabelGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y Continuar.
        /// </summary>
        public static string LabelGuardarContinuar {
            get {
                return ResourceManager.GetString("LabelGuardarContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y Salir.
        /// </summary>
        public static string LabelGuardarSalir {
            get {
                return ResourceManager.GetString("LabelGuardarSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string LabelId {
            get {
                return ResourceManager.GetString("LabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erp Académico.
        /// </summary>
        public static string LabelLeyendaERPAcademico {
            get {
                return ResourceManager.GetString("LabelLeyendaERPAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Académico.
        /// </summary>
        public static string LabelLeyendaERPAcademico2 {
            get {
                return ResourceManager.GetString("LabelLeyendaERPAcademico2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de Expedientes.
        /// </summary>
        public static string LabelLeyendaGestionExpedientes {
            get {
                return ResourceManager.GetString("LabelLeyendaGestionExpedientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestor Unir.
        /// </summary>
        public static string LabelLeyendaGestorUnir {
            get {
                return ResourceManager.GetString("LabelLeyendaGestorUnir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestor UNIR.
        /// </summary>
        public static string LabelLeyendaGestorUnir2 {
            get {
                return ResourceManager.GetString("LabelLeyendaGestorUnir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string LabelLimpiar {
            get {
                return ResourceManager.GetString("LabelLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        public static string LabelResultados {
            get {
                return ResourceManager.GetString("LabelResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leyendas.
        /// </summary>
        public static string LabelSeccionLeyenda {
            get {
                return ResourceManager.GetString("LabelSeccionLeyenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*).
        /// </summary>
        public static string RequiredSymbol {
            get {
                return ResourceManager.GetString("RequiredSymbol", resourceCulture);
            }
        }
    }
}
