//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstudioIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstudioIntegracionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Views.EstudioIntegracionStrings", typeof(EstudioIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string LabelActivo {
            get {
                return ResourceManager.GetString("LabelActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string LabelAnyo {
            get {
                return ResourceManager.GetString("LabelAnyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Plan de Estudio en el ERP Académico.
        /// </summary>
        public static string LabelDatosEstudioErp {
            get {
                return ResourceManager.GetString("LabelDatosEstudioErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Estudio en el Gestor UNIR.
        /// </summary>
        public static string LabelDatosEstudioGestor {
            get {
                return ResourceManager.GetString("LabelDatosEstudioGestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialización.
        /// </summary>
        public static string LabelEspecializacion {
            get {
                return ResourceManager.GetString("LabelEspecializacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string LabelEstudio {
            get {
                return ResourceManager.GetString("LabelEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Estudio.
        /// </summary>
        public static string LabelIdEstudio {
            get {
                return ResourceManager.GetString("LabelIdEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Plan de Estudio.
        /// </summary>
        public static string LabelIdPlanEstudio {
            get {
                return ResourceManager.GetString("LabelIdPlanEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string LabelPlan {
            get {
                return ResourceManager.GetString("LabelPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Estudio.
        /// </summary>
        public static string LabelPlanEstudio {
            get {
                return ResourceManager.GetString("LabelPlanEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Oficial.
        /// </summary>
        public static string LabelPlanOficial {
            get {
                return ResourceManager.GetString("LabelPlanOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rama.
        /// </summary>
        public static string LabelRama {
            get {
                return ResourceManager.GetString("LabelRama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rama de Conocimiento.
        /// </summary>
        public static string LabelRamaConocimiento {
            get {
                return ResourceManager.GetString("LabelRamaConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Estudio.
        /// </summary>
        public static string LabelTipoEstudio {
            get {
                return ResourceManager.GetString("LabelTipoEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Mapeos de Estudios.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Mapeo de Estudio.
        /// </summary>
        public static string LabelTitleCrear {
            get {
                return ResourceManager.GetString("LabelTitleCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Mapeo de Estudio.
        /// </summary>
        public static string LabelTitleEditar {
            get {
                return ResourceManager.GetString("LabelTitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string LabelTitulo {
            get {
                return ResourceManager.GetString("LabelTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título RUCT.
        /// </summary>
        public static string LabelTituloRuct {
            get {
                return ResourceManager.GetString("LabelTituloRuct", resourceCulture);
            }
        }
    }
}
