//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeriodoEstudioAsignaturaIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodoEstudioAsignaturaIntegracionStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Views.PeriodoEstudioAsignaturaIntegracionStrings", typeof(PeriodoEstudioAsignaturaIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Asignatura Ofertada.
        /// </summary>
        public static string BotonBuscarAsignaturaOfertada {
            get {
                return ResourceManager.GetString("BotonBuscarAsignaturaOfertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activa.
        /// </summary>
        public static string LabelActiva {
            get {
                return ResourceManager.GetString("LabelActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string LabelAsignatura {
            get {
                return ResourceManager.GetString("LabelAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura Ofertada.
        /// </summary>
        public static string LabelAsignaturaOfertadaErp {
            get {
                return ResourceManager.GetString("LabelAsignaturaOfertadaErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura Plan.
        /// </summary>
        public static string LabelAsignaturaPlanErp {
            get {
                return ResourceManager.GetString("LabelAsignaturaPlanErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Créditos.
        /// </summary>
        public static string LabelCreditos {
            get {
                return ResourceManager.GetString("LabelCreditos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Créditos.
        /// </summary>
        public static string LabelCreditosErp {
            get {
                return ResourceManager.GetString("LabelCreditosErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso.
        /// </summary>
        public static string LabelCurso {
            get {
                return ResourceManager.GetString("LabelCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso.
        /// </summary>
        public static string LabelCursoErp {
            get {
                return ResourceManager.GetString("LabelCursoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración Período Lectivo.
        /// </summary>
        public static string LabelDuracionPeriodoLectivoErp {
            get {
                return ResourceManager.GetString("LabelDuracionPeriodoLectivoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudio.
        /// </summary>
        public static string LabelEstudio {
            get {
                return ResourceManager.GetString("LabelEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Asignatura Ofertada.
        /// </summary>
        public static string LabelIdAsignaturaOfertadaErp {
            get {
                return ResourceManager.GetString("LabelIdAsignaturaOfertadaErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Período de Estudio.
        /// </summary>
        public static string LabelIdPeriodoEstudio {
            get {
                return ResourceManager.GetString("LabelIdPeriodoEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Per. Est. Asig..
        /// </summary>
        public static string LabelIdPeriodoEstudioAsignacion {
            get {
                return ResourceManager.GetString("LabelIdPeriodoEstudioAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Período Estudio Asignatura.
        /// </summary>
        public static string LabelIdPeriodoEstudioAsignatura {
            get {
                return ResourceManager.GetString("LabelIdPeriodoEstudioAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Plan Ofertado.
        /// </summary>
        public static string LabelIdPlanOfertadoErp {
            get {
                return ResourceManager.GetString("LabelIdPlanOfertadoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período Académico.
        /// </summary>
        public static string LabelPeriodoAcademico {
            get {
                return ResourceManager.GetString("LabelPeriodoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período Académico.
        /// </summary>
        public static string LabelPeriodoAcademicoErp {
            get {
                return ResourceManager.GetString("LabelPeriodoAcademicoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período Lectivo.
        /// </summary>
        public static string LabelPeriodoLectivo {
            get {
                return ResourceManager.GetString("LabelPeriodoLectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período Lectivo.
        /// </summary>
        public static string LabelPeriodoLectivoErp {
            get {
                return ResourceManager.GetString("LabelPeriodoLectivoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período Matrículación.
        /// </summary>
        public static string LabelPeriodoMatriculacion {
            get {
                return ResourceManager.GetString("LabelPeriodoMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan de Estudio.
        /// </summary>
        public static string LabelPlanEstudio {
            get {
                return ResourceManager.GetString("LabelPlanEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan de Estudio.
        /// </summary>
        public static string LabelPlanEstudioErp {
            get {
                return ResourceManager.GetString("LabelPlanEstudioErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la Asignatura Ofertada en el ERP Académico.
        /// </summary>
        public static string LabelSeccionAsignaturaOfertada {
            get {
                return ResourceManager.GetString("LabelSeccionAsignaturaOfertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Período de Estudio de Asignatura en el Gestor UNIR.
        /// </summary>
        public static string LabelSeccionPeriodoAsignatura {
            get {
                return ResourceManager.GetString("LabelSeccionPeriodoAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Asignatura.
        /// </summary>
        public static string LabelTipoAsignatura {
            get {
                return ResourceManager.GetString("LabelTipoAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Asignatura.
        /// </summary>
        public static string LabelTipoAsignaturaErp {
            get {
                return ResourceManager.GetString("LabelTipoAsignaturaErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Mapeo de Período de Estudio de Asignatura.
        /// </summary>
        public static string LabelTituloPaginaEdicion {
            get {
                return ResourceManager.GetString("LabelTituloPaginaEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Período Lectivo.
        /// </summary>
        public static string LabelUbicacionPeriodoLectivoErp {
            get {
                return ResourceManager.GetString("LabelUbicacionPeriodoLectivoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Mapeos de Períodos de Estudios de Asignaturas.
        /// </summary>
        public static string TitleListar {
            get {
                return ResourceManager.GetString("TitleListar", resourceCulture);
            }
        }
    }
}
