//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeriodoEstudioIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodoEstudioIntegracionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Views.PeriodoEstudioIntegracionStrings", typeof(PeriodoEstudioIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Período de Estudio.
        /// </summary>
        public static string BotonBuscarPeriodoEstudio {
            get {
                return ResourceManager.GetString("BotonBuscarPeriodoEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Plan Ofertado.
        /// </summary>
        public static string BotonBuscarPlanOfertadoErp {
            get {
                return ResourceManager.GetString("BotonBuscarPlanOfertadoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Periodo de Estudio en el Gestor UNIR.
        /// </summary>
        public static string LabelDatosPeriodoEstudioGestor {
            get {
                return ResourceManager.GetString("LabelDatosPeriodoEstudioGestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Plan Ofertado en el ERP Académico.
        /// </summary>
        public static string LabelDatosPlanOfertadoErp {
            get {
                return ResourceManager.GetString("LabelDatosPlanOfertadoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string LabelEstudio {
            get {
                return ResourceManager.GetString("LabelEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Período Estudio.
        /// </summary>
        public static string LabelIdPeriodoEstudio {
            get {
                return ResourceManager.GetString("LabelIdPeriodoEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Plan Ofertado.
        /// </summary>
        public static string LabelIdPlanOfertadoErp {
            get {
                return ResourceManager.GetString("LabelIdPlanOfertadoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período Académico.
        /// </summary>
        public static string LabelPeriodoAcademicoErp {
            get {
                return ResourceManager.GetString("LabelPeriodoAcademicoErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período Matrículación.
        /// </summary>
        public static string LabelPeriodoMatriculacion {
            get {
                return ResourceManager.GetString("LabelPeriodoMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Estudio.
        /// </summary>
        public static string LabelPlanEstudioErp {
            get {
                return ResourceManager.GetString("LabelPlanEstudioErp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Período de Estudio en el Gestor UNIR.
        /// </summary>
        public static string LabelSeccionPeriodoEstudio {
            get {
                return ResourceManager.GetString("LabelSeccionPeriodoEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Plan Ofertado en el ERP Académico.
        /// </summary>
        public static string LabelSeccionPlanOfertado {
            get {
                return ResourceManager.GetString("LabelSeccionPlanOfertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Mapeo de Período de Estudio.
        /// </summary>
        public static string LabelTituloPaginaAdicion {
            get {
                return ResourceManager.GetString("LabelTituloPaginaAdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Mapeo de Período de Estudio.
        /// </summary>
        public static string LabelTituloPaginaEdicion {
            get {
                return ResourceManager.GetString("LabelTituloPaginaEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Mapeos de Períodos de Estudios.
        /// </summary>
        public static string LabelTituloPaginaListado {
            get {
                return ResourceManager.GetString("LabelTituloPaginaListado", resourceCulture);
            }
        }
    }
}
