//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeriodoMatriculacionIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodoMatriculacionIntegracionStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Views.PeriodoMatriculacionIntegracionStrings", typeof(PeriodoMatriculacionIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Período Académico en el ERP Académico.
        /// </summary>
        public static string GrupoPeriodoAcademico {
            get {
                return ResourceManager.GetString("GrupoPeriodoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Período de Matriculación en el Gestor UNIR.
        /// </summary>
        public static string GrupoPeriodoMatriculacion {
            get {
                return ResourceManager.GetString("GrupoPeriodoMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año Académico.
        /// </summary>
        public static string LabelAñoAcademico {
            get {
                return ResourceManager.GetString("LabelAñoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaFin.
        /// </summary>
        public static string LabelFechaFin {
            get {
                return ResourceManager.GetString("LabelFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string LabelFechaInicio {
            get {
                return ResourceManager.GetString("LabelFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Período Académico.
        /// </summary>
        public static string LabelIdPeriodoAcademico {
            get {
                return ResourceManager.GetString("LabelIdPeriodoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Período Matriculación.
        /// </summary>
        public static string LabelIdPeriodoMatriculacion {
            get {
                return ResourceManager.GetString("LabelIdPeriodoMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro..
        /// </summary>
        public static string LabelNro {
            get {
                return ResourceManager.GetString("LabelNro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período Académico.
        /// </summary>
        public static string LabelPeriodoAcademico {
            get {
                return ResourceManager.GetString("LabelPeriodoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período de Matrículación.
        /// </summary>
        public static string LabelPeriodoMatriculacion {
            get {
                return ResourceManager.GetString("LabelPeriodoMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Mapeo de Período de Matriculación.
        /// </summary>
        public static string TitleCrear {
            get {
                return ResourceManager.GetString("TitleCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Mapeo de Período de Matriculación.
        /// </summary>
        public static string TitleEditar {
            get {
                return ResourceManager.GetString("TitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Mapeos de Períodos de Matriculación.
        /// </summary>
        public static string TitleListar {
            get {
                return ResourceManager.GetString("TitleListar", resourceCulture);
            }
        }
    }
}
