//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorMapeos.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlantillaEstudioIntegracionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlantillaEstudioIntegracionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorMapeos.Globalization.Views.PlantillaEstudioIntegracionStrings", typeof(PlantillaEstudioIntegracionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Plan de Estudio en el ERP Académico.
        /// </summary>
        public static string GrupoPlanEstudio {
            get {
                return ResourceManager.GetString("GrupoPlanEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Plantilla de Estudio en Gestión de Expedientes.
        /// </summary>
        public static string GrupoPlantillaEstudio {
            get {
                return ResourceManager.GetString("GrupoPlantillaEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string LabelAnyo {
            get {
                return ResourceManager.GetString("LabelAnyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string LabelEstudio {
            get {
                return ResourceManager.GetString("LabelEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Plan de Estudio.
        /// </summary>
        public static string LabelIdPlan {
            get {
                return ResourceManager.GetString("LabelIdPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Plantilla Estudio.
        /// </summary>
        public static string LabelIdPlantillaEstudio {
            get {
                return ResourceManager.GetString("LabelIdPlantillaEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Estudio.
        /// </summary>
        public static string LabelPlan {
            get {
                return ResourceManager.GetString("LabelPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Oficial.
        /// </summary>
        public static string LabelPlanOficial {
            get {
                return ResourceManager.GetString("LabelPlanOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla Estudio.
        /// </summary>
        public static string LabelPlantillaEstudio {
            get {
                return ResourceManager.GetString("LabelPlantillaEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rama de Conocimiento.
        /// </summary>
        public static string LabelRamaConocimiento {
            get {
                return ResourceManager.GetString("LabelRamaConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Estudio.
        /// </summary>
        public static string LabelTipoEstudio {
            get {
                return ResourceManager.GetString("LabelTipoEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Mapeo de Plantilla de Estudio.
        /// </summary>
        public static string LabelTitleCrear {
            get {
                return ResourceManager.GetString("LabelTitleCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Mapeo de Plantilla de Estudio.
        /// </summary>
        public static string LabelTitleEditar {
            get {
                return ResourceManager.GetString("LabelTitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Mapeos de Plantillas de Estudios.
        /// </summary>
        public static string LabelTitleListar {
            get {
                return ResourceManager.GetString("LabelTitleListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string LabelTitulo {
            get {
                return ResourceManager.GetString("LabelTitulo", resourceCulture);
            }
        }
    }
}
